Algoritmo "exer-S"


Var

 a, b, ad, sb, mu, di : real

Inicio

 escreva("Insira o valor de A:")
 leia(a)
 escreva("Insira o valor de B:")
 leia(b)

 ad <- a + b
 sb <- a - b
 mu <- a * b
 di <- a / b
 
 escreval("________________________")
 escreval("Adição de A e B =", ad)
 escreval("Subitração de A e B =", sb)
 escreval("Multiplicação de A e B =", mu)
 escreval("Divisão de A e B =", di)
Fimalgoritmo