Algoritmo "exer-O"
// ler quatro valores
// calcular a mult de 1º com 3º número
// calcular a soma 2º com o 4º número
// exibir o resultado
Var

a, b, c, d , p, s : inteiro

Inicio

 escreva("Insira o valor de A:")
 leia(a)

 escreva("Insira o valor de B:")
 leia(b)
 
 escreva("Insira o valor de C:")
 leia(c)
 
 escreva("Insira o valor de D:")
 leia(d)

 p <- a * c
 s <- b + d

 escreval("Produto de A e B = ", p)
 escreval("Soma de C e D = ", s)

Fimalgoritmo