Algoritmo "exer-h"

Var
 a, b, c, d, resto : inteiro

Inicio

escreval("Insira o valor de a, b, c, e d:")
leia(a,b,c,d)

//estru. seq. simples
se (a mod 2 = 0) e (a mod 3 = 0) entao
   escreval(a)
fimse

se (b mod 2 = 0) e (b mod 3 = 0) entao
   escreval(b)
fimse

se (c mod 2 = 0) e (c mod 3 = 0) entao
   escreval(c)
fimse

se (d mod 2 = 0) e (d mod 3 = 0) entao
   escreval(d)
fimse

Fimalgoritmo